Allarious

high

# Proposer can submit a faulty proof and avoid any transaction from getting finalized on-chain

## Summary
Proposer in the system has the ability to propose outputs via `proposeL2Output`. This helps the validation on-chain to make sure that a transaction was submitted to `L2toL1Messenger`. In the case where an output is faulty and does not match the actual L2 state, the challenger steps in and slashes the faulty proposer, taking some or all of his staked amount (probably in future updates). If a proposer misbehaves, it is expected to have no side-effects in the long term as there is a 7 days challenging period.

However, there is a way where the proposer can block any transaction from getting finalized on L1 chain, therefore locking all of the amounts sent to L2. Proposer will get caught by the challenger but it would be too late since the propose of the faulty state and blocking the target transaction can happen in one transaction by the dishonest proposer atomically. While proposer gets slashed, this is an extremely dangerous attack, where any amount of withdrawal and any number of transactions with funds can be locked!

## Vulnerability Detail
The expected flow for a withdrawal transaction would be that a transaction is mined in an L2 block (sent to the sequencer or trigger via another deposit transaction on chain), the state of the `L2toL1Messenger` is sent to `L2OutputOracle`, and the transaction gets proven on L1, allowing the user to finalize and execute the transaction after the `FINALIZATION_PERIOD_SECONDS` which is currently 7 days.

The code snippet blow from `proveWithdrawalTransaction`, is supposed to allow users to prove their transaction in two cases:
(1) Where the transaction has not been proven before.
(2) Where the transaction has been proven, but the `CHALLENGER` deleted the outputs to a certain index before the related output state.

```solidity
        require(
            provenWithdrawal.timestamp == 0 ||
                (_l2OutputIndex == provenWithdrawal.l2OutputIndex &&
                    outputRoot != provenWithdrawal.outputRoot),
            "OptimismPortal: withdrawal hash has already been proven"
        );
```
https://github.com/ethereum-optimism/optimism/blob/3f4b3c328153a8aa03611158b6984d624b17c1d9/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L194-L199

However, it does not take into account if a transaction that is being proved for the first time, is actually sent by **a faulty output, by a faulty prover, and in a blockheight that the transaction is not included yet!**. This means that a faulty proposer can do the following attack:

(1) - Finds out about a transaction that is going to be included on the L2 chain soon, and try to build its transaction hash by guessing the nonce (or it can just repeat for as many nonces as he wants in one transaction). If the proposer and sequencer are the same, this attack would cost much less!
(2) - Makes a list of txHashes he wants to attack.
(3) - Forge the state of `L2toL1Messenger`, where the list of transactions are marked as `true` in `sentMessages` storage.
(4) - Commit the forged storage output to the `L2OutputOracle`.
(5) - Prove all of the txHashes transactions on-chain via `proveWithdrawalTransaction`.

At this point the attack is done! All the transactions in the txHashes are proven while they do not still in a block on L2 chain. The flow however, will continue:

(6) The challenger quickly finds the faulty proposer, deleting the outputs until the faulty output.
(7) Transactions get included on the L2 chain. **This attack only works for the transactions that get included on the next set of checkpoints**
(8) Transactions try to prove themselves for the second time on chain (they were already proven once on the attacker), but they can't. According to the code snippet below, their proof should be in the `_l2OutputIndex` submitted by the dishonest proposer. While when they try to submit their transaction on the `_l2OutputIndex` storage root, since they transactions did not exist on the L2 chain by that time, will receive an error from the verification section by `SecureMerkleTrie.verifyInclusionProof` seen below:
```solidity
        require(
            SecureMerkleTrie.verifyInclusionProof(
                abi.encode(storageKey),
                hex"01",
                _withdrawalProof,
                _outputRootProof.messagePasserStorageRoot
            ),
            "OptimismPortal: invalid withdrawal inclusion proof"
        );
```
https://github.com/ethereum-optimism/optimism/blob/3f4b3c328153a8aa03611158b6984d624b17c1d9/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L215-L223

## Impact
The impact would be, since the transactions get mined on L2 in the future, any funds send to the `L2toL1Messenger` will be burnt for good without no outcome! This is a big threat for assets on L2, as they can be burnt by a faulty proposer in case they want to withdraw from the chain. It should be mentioned again that the transactions on L2 should be included after `_l2OutputIndex` submitted by the attacker, this is more dangerous for the withdrawals generating from the L1, since they need some time to be picked up by the nodes and the L1 itself. The proposer can attack as many transactions as he want as far as the block limit allows before he is challenged, therefore, he can either guess many nonces for the same transaction, or attack many transactions, or even a combination of both!

The impact goes way higher when the proposer is teamed up with the sequencer, this means that the same actor, can exactly know the nonces, and can make sure they land on the block after some checkpoint. Since at the start of the Optimism, these two actors are the same entity, it needs to be trusted by the users not to pull this attack off.

## Code Snippet

## Tool used
Manual Review

## Recommendation
